name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Health Check
        run: curl -s https://roadwatch-v3.onrender.com/health
